---
title: "Hackathon"
description: |
  A training opportunity in data analytics
  
  Additional details to be added soon!
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

In the group hackathon (13:00-18:00), we will be using data visualization **to understand how people perceive all sorts of technological and societal risks**, from nuclear energy to climate change! Participants will work in small groups of three to five people to produce stunning data visualizations using information on risk perception related to numerous risk sources.

## Data

We will use data from an ongoing project by [Zak Hussain](https://www.linkedin.com/in/zakir-a-s-hussain/), [Dirk Wulff](https://dwulff.github.io/about/), and [Rui Mata](https://matarui.org) that will be made publicly available shortly before the hackathon. 

| Variable | Description |
|:-------------|:-------------------------------------|
| `word` | Around 12K words contained in the intersection of the GloVe and SWOW vocabulary. |
| `cluster` | The group to which each word has been allocated by a clustering algorithm. |
| `risk_rating` | Mean of participant risk ratings given to each word on a scale of -100 (safe) to +100 (risky) |

**Psychometric Model**
The following are mean responses given on 7-point likert scale to the associated questions:
| `psych_voluntary` | Are individuals exposed to this risk voluntarily or involuntarily? (1=voluntary, 7=involuntary) |
| `psych_fatal` | How fatal are the consequences of this risk? (1=not-fatal, 7=fatal) |
| `psych_immediate` | Is death from this risk immediate or delayed? (1=immediate, 7=delayed) |
| `psych_dread` | Is this a risk that individuals can reason about calmly or is it one that they have great dread for? (1=calm, 7=dread) |
| `psych_catastrophic` | Is this a risk that kills one person at a time (chronic) or a risk that kills large numbers of people at once (catastrophic)? (1=chronic, 7=catastrophic) |
| `psych_controllable` |  Is this risk controllable or uncontrollable for the individual exposed to this risk? (1=controllable, 7=uncontrollable) |
| `psych_known_sci` | Is this risk known or unknown to science,Is this risk known or unknown to the individuals exposed to this risk? (1=Known, 7=Unknown)|
| `psych_known` | Is this risk known or unkown to the individuals exposed to this risk? (1=known, 7=unkown) |
| `psych_new` | Is this risk new or old? (1=new, 7=old) |

*| 'psych_pc[1-9]' | 9 principle components obtained via principle component anlaysis of the above psychometric dimensions |

| `in_Fisch` | Boolean indicating whether the word is contained in Fischhoff et al. (1978). |

| `psych_pred_risk` | Predicted riskiness of each word according to 9 psychometric dimensions (above) |

**Semnantic Models**
The following are predictions from (i) SWOW and (ii) GloVe - semantic (embedding) models respectively trained on (i) free association and (ii) online text data. In addition to predicting the risk ratings, they predict the 9 psychometric dimensions listed above. 
| `[glove/swow]_pred_risk` | 

## Tasks


