---
title: "R Training"
description: |
  Preparing for the hackathon
  
  Additional details to be added soon!
output: 
  distill::distill_article:
    md_extensions: +emoji
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## R Training Class

If you are a :hatching_chick: in R, you will especially benefit from our training class! In the morning of the hackathon, we will be offering an **optional training class (9:00-12:00)**. Together, we will explore convenient project management in R, experience efficient collaboration through GitHub, dive into the world of tidyverse and look at some of the functions and plots that will be most useful for the hackathon. **Psychology students and researchers at the Faculty of Psychology** planning to join the hackathon are very welcome to this training session!

If you are new to R or need a refresher, we recommend you to go through the topics in [R Training Website for CDS Students](https://cdsbasel.github.io/rtraining/), where we have compiled different online materials for basic R skills. 

<aside>
Topics 2 and 7-10 will especially come in handy!
</aside>

Please indicate whether you will be joining the training class in your [registration](https://forms.gle/4xATFZiGKfQoDNZK8) (open from October 17th till November 7th).